### ISSUE TITLE
New Logo For Note

### ISSUE THREAD

**Issue by zularizal** [0quietwater0/Note#1]
Hi @0quietwater0 , I want to contribute to your project, I want to design a logo and icons for your project and it's free, do you want it?

**Comment by 0quietwater0** [comment]
ok ,Thanks

**Comment by zularizal** [comment]
Okay, I'll design it

**Comment by zularizal** [comment]
hi @0quietwater0 , What do you think, which one do you like? If anything needs to be changed, please let me know

![llogo](https://user-images.githubusercontent.com/38547278/39954895-7d30a878-55f1-11e8-8bc5-63225ad30c88.png)

**Comment by 0quietwater0** [comment]
I like all of them and I perfer the first one.

**Comment by zularizal** [comment]
All right, wait a minute I'll upload it to drive.

**Comment by 0quietwater0** [comment]
Ok,  I am look forward to further cooperation with you.

**Comment by zularizal** [comment]
Hi @0quietwater0 , hi i've uploaded it, please check your link in this drive

https://drive.google.com/open?id=1XBSLud9bIK74eoQNgfqcTgd0QNW_tpxQ

And I've sent a pull request for you #2

**Comment by 0quietwater0** [comment]
@zularizal I have merged them.

**Comment by zularizal** [comment]
Okay @0quietwater0 , i will close this issue
